name: app_v1
description: "PutraBus - A Near Real-time Bus Tracking App"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  url_launcher: ^6.0.12
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true



